import {
  ArchiveBoxIcon,
  BookOpenIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
  CakeIcon,
  ChartBarIcon,
  CodeBracketIcon,
  ComputerDesktopIcon,
  CurrencyDollarIcon,
  FaceSmileIcon,
  GiftIcon,
  HandThumbUpIcon,
  HeartIcon,
  MapIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  PaintBrushIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  UserIcon,
  UsersIcon,
  WalletIcon,
} from "@heroicons/react/24/outline";


export const icons = [
  BookOpenIcon,
  PaintBrushIcon,
  UserIcon,
  UsersIcon,
  ShoppingCartIcon,
  CakeIcon,
  FaceSmileIcon,
  HeartIcon,
  MusicalNoteIcon,
  WalletIcon,
  ShoppingBagIcon,
  NewspaperIcon,
  MapIcon,
  HandThumbUpIcon,
  GiftIcon,
  CurrencyDollarIcon,
  ComputerDesktopIcon,
  ChartBarIcon,
  ArchiveBoxIcon,
  CodeBracketIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
];


